name: esbuild-plugin-version-injector
packagePath: .
commitMessageTemplate: 'chore(release): release {{new-version}}'
tagTemplate: v{{new-version}}
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: favware/esbuild-plugin-version-injector
gitHostVariant: github
